version: "3.8"

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      # Telegram Bot Configuration
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      TELEGRAM_ALLOWED_USERS: "${TELEGRAM_ALLOWED_USERS}"
      TELEGRAM_ADMIN_CHAT_ID: "${TELEGRAM_ADMIN_CHAT_ID}"
      TELEGRAM_NOTIFICATION_CHAT_ID: "${TELEGRAM_NOTIFICATION_CHAT_ID}"

      # qBittorrent Configuration (using zerotier network service names)
      QBIT_HOST: "qbittorrent"
      QBIT_PORT: "8080"
      QBIT_USERNAME: "${QBIT_USER:-admin}"
      QBIT_PASSWORD: "${QBIT_PASS:-adminadmin}"
      QBIT_HTTPS: "false"

      # Jackett Configuration (using zerotier network service names) 
      JACKETT_HOST: "jackett"
      JACKETT_PORT: "9117"
      JACKETT_API_KEY: "${JACKETT_API_KEY}"
      JACKETT_HTTPS: "false"

      # Download Paths (D: drive for direct storage)
      DOWNLOAD_PATH: "D:\\downloads"
      COMPLETED_PATH: "D:\\downloads\\completed"
      TEMP_PATH: "D:\\downloads\\temp"

      # Search Configuration
      SEARCH_LIMIT: "50"
      MIN_SEEDERS: "1"
      SEARCH_TIMEOUT: "30"

      # Application Configuration
      DEBUG: "false"
      LOG_LEVEL: "INFO"
    volumes:
      - "${DOWNLOAD_PATH:-D:\\downloads}:/app/downloads"
    depends_on:
      - qbittorrent
      - flaresolverr
    networks:
      - zerotier

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8080
      - QBT_WEBUI_USERNAME=${QBIT_USER:-admin}
      - QBT_WEBUI_PASSWORD=${QBIT_PASS:-adminadmin}
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - "${DOWNLOAD_PATH:-D:\\downloads}:/downloads"
      - "${QBIT_CONFIG_PATH:-D:\\qbittorrent-config}:/config"
    networks:
      - zerotier

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Warsaw
    ports:
      - "8191:8191"    # FlareSolverr Web API
    networks:
      - zerotier

networks:
  zerotier:
    external: true


