version: "3.8"

services:
  telegram-bot:
    build:
      context: .
      dockerfile: dockerfile_final
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      # Telegram Bot Configuration
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      ADMIN_USER_ID: "${ADMIN_USER_ID}"

      # Jackett Configuration (optional - for torrent search)
      JACKETT_URL: "${JACKETT_URL:-http://jackett:9117}"
      JACKETT_API_KEY: "${JACKETT_API_KEY}"

      # Popular indexers for torrent search
      JACKETT_INDEXERS: "${JACKETT_INDEXERS:-yts,nyaa,eztv,1337x,torrentgalaxy,thepiratebay,torlock,limetorrents,glodls,bitsearch,torrentfunk,magnetdl,yourbittorrent,zooqle,torrentdownloads,linuxtracker,anidex,animetosho,idope,ettv}"

      # Performance tuning
      JACKETT_CONNECT_TIMEOUT: "${JACKETT_CONNECT_TIMEOUT:-3}"
      JACKETT_READ_TIMEOUT: "${JACKETT_READ_TIMEOUT:-12}"
      JACKETT_MAX_WORKERS: "${JACKETT_MAX_WORKERS:-8}"
      JACKETT_RESULT_LIMIT: "${JACKETT_RESULT_LIMIT:-5}"

      # qBittorrent Configuration
      QBIT_HOST: "qbittorrent"
      QBIT_PORT: "8080"
      QBIT_USER: "${QBIT_USER:-admin}"
      QBIT_PASS: "${QBIT_PASS:-adminadmin}"
    volumes:
      - downloads:/app/downloads
      - "${DOWNLOAD_PATH:-./downloads}:/app/downloads"
    depends_on:
      - qbittorrent      
    networks:
      - torrent-network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8080
      - QBT_WEBUI_USERNAME=${QBIT_USER:-admin}
      - QBT_WEBUI_PASSWORD=${QBIT_PASS:-adminadmin}
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - downloads:/downloads
      - qbitconfig:/config
      - "${DOWNLOAD_PATH:-./downloads}:/downloads"
      - "${QBIT_CONFIG_PATH:-./qbittorrent-config}:/config"
    networks:
      - torrent-network

networks:
  torrent-network:
    external: false

volumes:
  downloads:
  qbitconfig:
