version: "3.8"

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"

      # qBittorrent creds
      QBIT_HOST: "qbittorrent"
      QBIT_PORT: "8080"
      QBIT_USER: "${QBIT_USER:-admin}"
      QBIT_PASS: "${QBIT_PASS:-adminadmin}"
    volumes:
      - downloads:/app/downloads
    depends_on:
      - qbittorrent      
    networks:
      - torrent-network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8080
      - QBT_WEBUI_USERNAME=${QBIT_USER:-admin}
      - QBT_WEBUI_PASSWORD=${QBIT_PASS:-adminadmin}
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - downloads:/downloads
      - qbitconfig:/config
    networks:
      - torrent-network

networks:
  torrent-network:

volumes:
  downloads:
  qbitconfig:
