version: "3.8"

# Personal/simplified docker-compose configuration
# Uses localhost for all connections to avoid network issues

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      
      # Using localhost for simplicity
      JACKETT_URL: "http://localhost:9117"
      JACKETT_API_KEY: "${JACKETT_API_KEY}"
      
      # Popular indexers
      JACKETT_INDEXERS: "yts,nyaa,eztv,1337x,torrentgalaxy,thepiratebay,torlock,limetorrents,glodls,bitsearch"
      
      # Speed tuning
      JACKETT_CONNECT_TIMEOUT: "3"
      JACKETT_READ_TIMEOUT: "12"
      JACKETT_MAX_WORKERS: "4"
      JACKETT_RESULT_LIMIT: "5"
      
      # qBittorrent using localhost
      QBIT_HOST: "localhost"
      QBIT_PORT: "8080"
      QBIT_USER: "admin"
      QBIT_PASS: "adminadmin"
    volumes:
      - "${DOWNLOAD_PATH:-D:\\downloads}:/app/downloads"
    network_mode: host
    depends_on:
      - qbittorrent
      - flaresolverr

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8080
      - QBT_WEBUI_USERNAME=admin
      - QBT_WEBUI_PASSWORD=adminadmin
    volumes:
      - "${DOWNLOAD_PATH:-D:\\downloads}:/downloads"
      - "${QBIT_CONFIG_PATH:-D:\\qbittorrent-config}:/config"
    network_mode: host

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Warsaw
    network_mode: host
