version: "3.8"

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: "8415463111:AAFPN2GJoqayGtvcQpUYwhzyUFJGbmKTIPw"

      # Jackett (running in your other compose on the same network)
      JACKETT_URL: "http://jackett:9117"
      JACKETT_API_KEY: "gf72swxqzum06ifwsuya4uvvvmsdh9xd"

      # 🔥 20 most popular indexers (must be added/enabled in Jackett)
      JACKETT_INDEXERS: "yts,nyaa,eztv,1337x,torrentgalaxy,thepiratebay,torlock,limetorrents,glodls,bitsearch,torrentfunk,magnetdl,yourbittorrent,zooqle,torrentdownloads,linuxtracker,anidex,animetosho,idope,ettv"

      # Speed tuning
      JACKETT_CONNECT_TIMEOUT: "3"
      JACKETT_READ_TIMEOUT: "12"
      JACKETT_MAX_WORKERS: "8"
      JACKETT_RESULT_LIMIT: "5"

      # qBittorrent creds
      QBIT_HOST: "qbittorrent"
      QBIT_PORT: "8080"
      QBIT_USER: "admin"
      QBIT_PASS: "adminadmin"
    volumes:
      - "D:/Music:/app/downloads"
    depends_on:
      - qbittorrent
      - flaresolverr
    networks:
      - zerotier

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8080
      - QBT_WEBUI_USERNAME=admin
      - QBT_WEBUI_PASSWORD=adminadmin
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - "D:/Music:/downloads"
      - "D:/qbittorrent-config:/config"
    networks:
      - zerotier

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Warsaw
    ports:
      - "8191:8191"    # FlareSolverr Web API
    networks:
      - zerotier

networks:
  zerotier:
    external: true
