services:
  telegram-bot:
    build:
      context: .
      dockerfile: dockerfile_final
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: "8415463111:AAHfOuL811q_ZGyODB9vy0-h8nYkWnj4ysg"
      QBIT_HOST: "qbittorrent"
      QBIT_PORT: "8080"
      QBIT_USER: "admin"
      QBIT_PASS: "adminadmin"
    volumes:
      - downloads:/app/downloads
    depends_on:
      - qbittorrent      
    networks:
      - torrent-network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8080
      - QBT_WEBUI_USERNAME=admin
      - QBT_WEBUI_PASSWORD=adminadmin
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - downloads:/downloads
      - qbitconfig:/config
    networks:
      - torrent-network

networks:
  torrent-network:

volumes:
  downloads:
  qbitconfig:
